language: python

os:
  - linux
  # Travis-ci doesn't support osx + python yet.
  # - osx
  
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - make init
  - make install

before_script:
  - make flake8

script: make test
