language: python
dist: xenial
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- make init
- make install
before_script:
- make flake8
script: make test
deploy:
  matrix:
  - provider: pypi
    user: nextdoor
    password:
      secure: DwbX/dZcX9e1/UmmQiT+tUdlrBzZKpDGXLiN8d5Vb2L8WBZmW3OP22GUHSGqpwmo5gmJZbVng04F0YoUnwutoj3ipOQFFo2Xsq0AVqiiMc9OFUa4HbfpxU2WzsRdIE71nkbgMNplHPKvOgswqci97e7OhDGPDtX4ZOWAjOn7ctmcHWhD6CweIiZffcL4cNARD22zZAaUtru8pWloPoHoYHY37aDCZJJR/8YmYrqG5V1zkadmWU1SaDvFfd/mlnEhEEtM5X3auEmty7PI+AOyfyfAQLt1GsiHeAq15CCUf/VBrKdn0j/PVYYbM4d7+CJgtxUI5k8rOgT4s3qXzU4NFlip2uf3FxqRSKKKQWDOmzEgXm4ohcYcRpVXgFqkFgM6jLPoObORzcYcm9PN9qgQTtDyfMy97gDDJmx43EN0ZDdctCFmbh0RTwchMV2/EWzl13tflB7Bv8qZocZZS80dSloknsnDfHlhYl9PHkXzzkTofCp0/8PQy54xW8whkiphEKZEpW9uoWQVzfcJiXWelBIYV+V2gCsI5ltX+AGPwGCLGlTT8XBT6wqR+0WbWydn4RWAPnlRymz6Wp1+uusobyNbQRfSjt2/Na/X4lzUFMu3tq2kpfeCBwV8t6yFrcoraMDYJSmBTqWDHstb+Ndoz8AChPkohtRZnsdik8kLWNI=
    on:
      branch: pypi
      python: '3.6'
    distributions: sdist bdist_wheel
    skip_cleanup: true
  password:
    secure: EwW1NDigDCzui3fhNW/iiM8uQd0FNgQWXnJlgSnDMDrtJ2xKgy/JnOQktGVIkVAXL6qQ1VGZg2IBpz+cW+M7z+aoLjm4kvET7LmBMM9fuXpxP+m6LUyxOlGM+RzFw33aqtRoonwQyS0CXuY4+oKpUe1RP3Nze0L30w44RSmBS4z5J1KqB98piXx3aJhxI9ijafdHS7YAYymE7LR2eo6TQGVKuUQGDgz0X+RvRqwN3NrQ6tH0cKTFNbwD/tnojK6jSzNGeeYF0loON7pNCKaMt9cZwoEFK5xtx5Bky8vGOpM2NSmgobh1g368DRLZgba4iwdlFlxtgdyBzM8pi/os3nre/Z66+NFWOb3x7//xctqVzjN+O84J9BGv9ZlFMESu+xArWIbjItQUToeDHMa2LhxPsFC4BRLyH7LM2eFqQygFcErO8qs5jBNr12SuZdkKBXpn8FiL7nrYEW88Lm8HJKQRybcAQnNb9yRmAxPwKjEArGk9FiJD56fMzqIzybT9oBt4VQZlRsaX454Gay4EoY1aD/lvpIbh+58VJvWMss1I9jD9PqlN5jDXgDVUk7NzGwz9HNZHV/1Y16iNu6a4j7Rftu+M9zES++C0OyKdL7ehyxV13CHgXZiWRinmzKSpYaTxw+IgVGrbFdyFO6YScTIagbbrV3i2ImmGfEw9wR8=
